export const spanishWords = [
  // Animales
  'LEÓN', 'ÁGUILA', 'TIBURÓN', 'SERPIENTE', 'ELEFANTE', 'TIGRE', 'OSO', 'LOBO', 'GATO', 'PERRO',
  'CABALLO', 'VACA', 'CERDO', 'OVEJA', 'GALLINA', 'PATO', 'CONEJO', 'RATÓN', 'MURCIÉLAGO', 'ARAÑA',
  'ABEJA', 'MOSCA', 'MARIPOSA', 'HORMIGA', 'PULPO', 'BALLENA', 'DELFÍN', 'TORTUGA', 'COCODRILO', 'CANGURO',
  
  // Objetos cotidianos
  'MESA', 'SILLA', 'CAMA', 'PUERTA', 'VENTANA', 'RELOJ', 'TELÉFONO', 'ORDENADOR', 'LIBRO', 'LÁPIZ',
  'PAPEL', 'TIJERAS', 'CUCHILLO', 'TENEDOR', 'CUCHARA', 'PLATO', 'VASO', 'BOTELLA', 'LLAVE', 'CANDADO',
  'MARTILLO', 'CLAVO', 'TORNILLO', 'SIERRA', 'ESCALERA', 'CUERDA', 'CADENA', 'ANILLO', 'COLLAR', 'RELOJ',
  
  // Lugares
  'CASA', 'ESCUELA', 'HOSPITAL', 'BANCO', 'PARQUE', 'PLAYA', 'MONTAÑA', 'RÍO', 'LAGO', 'BOSQUE',
  'DESIERTO', 'CIUDAD', 'PUEBLO', 'CASTILLO', 'TORRE', 'PUENTE', 'IGLESIA', 'MUSEO', 'TEATRO', 'CINE',
  'ESTADIO', 'PISCINA', 'GIMNASIO', 'BIBLIOTECA', 'RESTAURANTE', 'HOTEL', 'AEROPUERTO', 'ESTACIÓN', 'PUERTO', 'FARO',
  
  // Profesiones
  'DOCTOR', 'ENFERMERA', 'PROFESOR', 'POLICÍA', 'BOMBERO', 'PILOTO', 'CAPITÁN', 'SOLDADO', 'JUEZ', 'ABOGADO',
  'ARQUITECTO', 'INGENIERO', 'CIENTÍFICO', 'ARTISTA', 'MÚSICO', 'ACTOR', 'ESCRITOR', 'PERIODISTA', 'FOTÓGRAFO', 'CHEF',
  'CAMARERO', 'MECÁNICO', 'ELECTRICISTA', 'FONTANERO', 'CARPINTERO', 'PINTOR', 'JARDINERO', 'AGRICULTOR', 'PESCADOR', 'MINERO',
  
  // Naturaleza
  'SOL', 'LUNA', 'ESTRELLA', 'NUBE', 'LLUVIA', 'NIEVE', 'VIENTO', 'TORMENTA', 'RAYO', 'TRUENO',
  'ARCOÍRIS', 'FUEGO', 'AGUA', 'TIERRA', 'AIRE', 'HIELO', 'VAPOR', 'HUMO', 'CENIZA', 'POLVO',
  'ARENA', 'PIEDRA', 'ROCA', 'CRISTAL', 'DIAMANTE', 'ORO', 'PLATA', 'HIERRO', 'MADERA', 'HOJA',
  
  // Cuerpo humano
  'CABEZA', 'OJO', 'NARIZ', 'BOCA', 'OREJA', 'PELO', 'CUELLO', 'HOMBRO', 'BRAZO', 'MANO',
  'DEDO', 'PECHO', 'ESPALDA', 'ESTÓMAGO', 'PIERNA', 'RODILLA', 'PIE', 'CORAZÓN', 'CEREBRO', 'SANGRE',
  
  // Alimentos
  'PAN', 'LECHE', 'QUESO', 'HUEVO', 'CARNE', 'PESCADO', 'POLLO', 'ARROZ', 'PASTA', 'PIZZA',
  'SOPA', 'ENSALADA', 'FRUTA', 'MANZANA', 'NARANJA', 'PLÁTANO', 'UVA', 'FRESA', 'LIMÓN', 'TOMATE',
  'PATATA', 'CEBOLLA', 'AJO', 'ZANAHORIA', 'LECHUGA', 'CHOCOLATE', 'HELADO', 'PASTEL', 'GALLETA', 'CAFÉ',
  
  // Transporte
  'COCHE', 'AUTOBÚS', 'TREN', 'AVIÓN', 'BARCO', 'BICICLETA', 'MOTO', 'CAMIÓN', 'TAXI', 'METRO',
  'TRANVÍA', 'HELICÓPTERO', 'COHETE', 'SUBMARINO', 'YATE', 'CANOA', 'PATINETE', 'TRINEO', 'GLOBO', 'PARACAÍDAS',
  
  // Deportes y juegos
  'PELOTA', 'FÚTBOL', 'BALONCESTO', 'TENIS', 'GOLF', 'BÉISBOL', 'VOLEIBOL', 'NATACIÓN', 'ATLETISMO', 'BOXEO',
  'AJEDREZ', 'CARTAS', 'DADO', 'CASINO', 'LOTERÍA', 'PREMIO', 'MEDALLA', 'TROFEO', 'CAMPEONATO', 'EQUIPO',
  
  // Conceptos abstractos
  'AMOR', 'ODIO', 'PAZ', 'GUERRA', 'VIDA', 'MUERTE', 'TIEMPO', 'ESPACIO', 'FUERZA', 'PODER',
  'LIBERTAD', 'JUSTICIA', 'VERDAD', 'MENTIRA', 'SUEÑO', 'PESADILLA', 'ESPERANZA', 'MIEDO', 'ALEGRÍA', 'TRISTEZA',
  'SUERTE', 'DESTINO', 'MAGIA', 'MISTERIO', 'SECRETO', 'HISTORIA', 'FUTURO', 'PRESENTE', 'PASADO', 'ETERNIDAD',
  
  // Tecnología
  'INTERNET', 'COMPUTADORA', 'PANTALLA', 'TECLADO', 'RATÓN', 'CABLE', 'BATERÍA', 'CÁMARA', 'MICRÓFONO', 'ALTAVOZ',
  'ROBOT', 'SATÉLITE', 'ANTENA', 'SEÑAL', 'CÓDIGO', 'PROGRAMA', 'VIRUS', 'CONTRASEÑA', 'ARCHIVO', 'CARPETA',
  
  // Ropa y accesorios
  'CAMISA', 'PANTALÓN', 'VESTIDO', 'FALDA', 'ZAPATO', 'BOTA', 'CALCETÍN', 'SOMBRERO', 'GORRA', 'BUFANDA',
  'GUANTE', 'CINTURÓN', 'CORBATA', 'CHAQUETA', 'ABRIGO', 'JERSEY', 'PIJAMA', 'TRAJE', 'UNIFORME', 'DISFRAZ',
  
  // Herramientas y utensilios
  'LÁPIZ', 'BOLÍGRAFO', 'GOMA', 'REGLA', 'COMPÁS', 'PINCEL', 'PINTURA', 'LIENZO', 'ESCULTURA', 'FOTOGRAFÍA',
  'CEPILLO', 'PEINE', 'ESPEJO', 'JABÓN', 'TOALLA', 'ESPONJA', 'ESCOBA', 'FREGONA', 'CUBO', 'ASPIRADORA',
  
  // Música y arte
  'MÚSICA', 'CANCIÓN', 'MELODÍA', 'RITMO', 'NOTA', 'PIANO', 'GUITARRA', 'VIOLÍN', 'TAMBOR', 'FLAUTA',
  'ORQUESTA', 'CONCIERTO', 'ÓPERA', 'BALLET', 'DANZA', 'PINTURA', 'DIBUJO', 'COLOR', 'FORMA', 'LÍNEA',
  
  // Medicina y salud
  'MEDICINA', 'PASTILLA', 'JARABE', 'INYECCIÓN', 'VACUNA', 'VENDAJE', 'YESO', 'MULETA', 'SILLA DE RUEDAS', 'AMBULANCIA',
  'CIRUGÍA', 'RADIOGRAFÍA', 'ANÁLISIS', 'RECETA', 'FARMACIA', 'HOSPITAL', 'CLÍNICA', 'CONSULTORIO', 'EMERGENCIA', 'CURA',
  
  // Economía y negocios
  'DINERO', 'MONEDA', 'BILLETE', 'TARJETA', 'CHEQUE', 'CUENTA', 'AHORRO', 'PRÉSTAMO', 'DEUDA', 'INTERÉS',
  'BANCO', 'CAJERO', 'MERCADO', 'TIENDA', 'PRECIO', 'DESCUENTO', 'OFERTA', 'VENTA', 'COMPRA', 'NEGOCIO',
  
  // Educación
  'ALUMNO', 'ESTUDIANTE', 'MAESTRO', 'CLASE', 'LECCIÓN', 'EXAMEN', 'NOTA', 'TÍTULO', 'DIPLOMA', 'UNIVERSIDAD',
  'COLEGIO', 'INSTITUTO', 'ACADEMIA', 'CURSO', 'ASIGNATURA', 'MATEMÁTICAS', 'CIENCIA', 'HISTORIA', 'GEOGRAFÍA', 'IDIOMA',
  
  // Emociones y sentimientos
  'FELICIDAD', 'ENFADO', 'SORPRESA', 'ASCO', 'ENVIDIA', 'CELOS', 'ORGULLO', 'VERGÜENZA', 'CULPA', 'NOSTALGIA',
  'EMOCIÓN', 'PASIÓN', 'DESEO', 'ANSIEDAD', 'ESTRÉS', 'CALMA', 'SERENIDAD', 'EUFORIA', 'MELANCOLÍA', 'APATÍA'
];

export function getRandomWords(count: number): string[] {
  const shuffled = [...spanishWords].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}